-- 
-- Regiones
--

INSERT INTO prograweb.modulologin_REGION VALUES 	(1,'Arica y Parinacota','XV');
INSERT INTO prograweb.modulologin_REGION VALUES 	(2,'Tarapacá','I');
INSERT INTO prograweb.modulologin_REGION VALUES 	(3,'Antofagasta','II');
INSERT INTO prograweb.modulologin_REGION VALUES 	(4,'Atacama','III');
INSERT INTO prograweb.modulologin_REGION VALUES 	(5,'Coquimbo','IV');
INSERT INTO prograweb.modulologin_REGION VALUES 	(6,'Valparaiso','V');
INSERT INTO prograweb.modulologin_REGION VALUES 	(7,'Metropolitana de Santiago','RM');
INSERT INTO prograweb.modulologin_REGION VALUES 	(8, 'Libertador General Bernardo O''Higgins','VI');
INSERT INTO prograweb.modulologin_REGION VALUES 	(9,'Maule','VII');
INSERT INTO prograweb.modulologin_REGION VALUES 	(10,'Biobío','VIII');
INSERT INTO prograweb.modulologin_REGION VALUES 	(11,'La Araucanía','IX');
INSERT INTO prograweb.modulologin_REGION VALUES 	(12,'Los Ríos','XIV');
INSERT INTO prograweb.modulologin_REGION VALUES 	(13,'Los Lagos','X');
INSERT INTO prograweb.modulologin_REGION VALUES 	(14,'Aysén del General Carlos Ibáñez del Campo','XI');
INSERT INTO prograweb.modulologin_REGION VALUES 	(15,'Magallanes y de la Antártica Chilena','XII');

-- 
-- provincias
-- 

insert into prograweb.modulologin_provincia values	(1,'Arica',1);
insert into prograweb.modulologin_provincia values	(2,'Parinacota',1);
insert into prograweb.modulologin_provincia values	(3,'Iquique',2);
insert into prograweb.modulologin_provincia values	(4,'El Tamarugal',2);
insert into prograweb.modulologin_provincia values	(5,'Antofagasta',3);
insert into prograweb.modulologin_provincia values	(6,'El Loa',3);
insert into prograweb.modulologin_provincia values	(7,'Tocopilla',3);
insert into prograweb.modulologin_provincia values	(8,'Chañaral',4);
insert into prograweb.modulologin_provincia values	(9,'Copiapó',4);
insert into prograweb.modulologin_provincia values	(10,'Huasco',4);
insert into prograweb.modulologin_provincia values	(11,'Choapa',5);
insert into prograweb.modulologin_provincia values	(12,'Elqui',5);
insert into prograweb.modulologin_provincia values	(13,'Limarí',5);
insert into prograweb.modulologin_provincia values	(14,'Isla de Pascua',6);
insert into prograweb.modulologin_provincia values	(15,'Los Andes',6);
insert into prograweb.modulologin_provincia values	(16,'Petorca',6);
insert into prograweb.modulologin_provincia values	(17,'Quillota',6);
insert into prograweb.modulologin_provincia values	(18,'San Antonio',6);
insert into prograweb.modulologin_provincia values	(19,'San Felipe de Aconcagua',6);
insert into prograweb.modulologin_provincia values	(20,'Valparaiso',6);
insert into prograweb.modulologin_provincia values	(21,'Chacabuco',7);
insert into prograweb.modulologin_provincia values	(22,'Cordillera',7);
insert into prograweb.modulologin_provincia values	(23,'Maipo',7);
insert into prograweb.modulologin_provincia values	(24,'Melipilla',7);
insert into prograweb.modulologin_provincia values	(25,'Santiago',7);
insert into prograweb.modulologin_provincia values	(26,'Talagante',7);
insert into prograweb.modulologin_provincia values	(27,'Cachapoal',8);
insert into prograweb.modulologin_provincia values	(28,'Cardenal Caro',8);
insert into prograweb.modulologin_provincia values	(29,'Colchagua',8);
insert into prograweb.modulologin_provincia values	(30,'Cauquenes',9);
insert into prograweb.modulologin_provincia values	(31,'Curicó',9);
insert into prograweb.modulologin_provincia values	(32,'Linares',9);
insert into prograweb.modulologin_provincia values	(33,'Talca',9);
insert into prograweb.modulologin_provincia values	(34,'Arauco',10);
insert into prograweb.modulologin_provincia values	(35,'Bio Bío',10);
insert into prograweb.modulologin_provincia values	(36,'Concepción',10);
insert into prograweb.modulologin_provincia values	(37,'Ñuble',10);
insert into prograweb.modulologin_provincia values	(38,'Cautín',11);
insert into prograweb.modulologin_provincia values	(39,'Malleco',11);
insert into prograweb.modulologin_provincia values	(40,'Valdivia',12);
insert into prograweb.modulologin_provincia values	(41,'Ranco',12);
insert into prograweb.modulologin_provincia values	(42,'Chiloé',13);
insert into prograweb.modulologin_provincia values	(43,'Llanquihue',13);
insert into prograweb.modulologin_provincia values	(44,'Osorno',13);
insert into prograweb.modulologin_provincia values	(45,'Palena',13);
insert into prograweb.modulologin_provincia values	(46,'Aisén',14);
insert into prograweb.modulologin_provincia values	(47,'Capitán Prat',14);
insert into prograweb.modulologin_provincia values	(48,'Coyhaique',14);
insert into prograweb.modulologin_provincia values	(49,'General Carrera',14);
insert into prograweb.modulologin_provincia values	(50,'Antártica Chilena',15);
insert into prograweb.modulologin_provincia values	(51,'Magallanes',15);
insert into prograweb.modulologin_provincia values	(52,'Tierra del Fuego',15);
insert into prograweb.modulologin_provincia values	(53,'Última Esperanza',15);
prograweb.modulologin_
--prograweb.modulologin_
-- comunasprograweb.modulologin_
--prograweb.modulologin_

INSERT INTO login_comuna VALUES (1,'Arica');
insert into login_comuna values	(2,'Camarones');
insert into login_comuna values	(3,'General Lagos');
insert into login_comuna values	(4,'Putre');
insert into login_comuna values	(5,'Alto Hospicio');
insert into login_comuna values	(6,'Iquique');
insert into login_comuna values	(7,'Camiña');
insert into login_comuna values	(8,'Colchane');
insert into login_comuna values	(9,'Huara');
insert into login_comuna values	(10,'Pica');
insert into login_comuna values	(11,'Pozo Almonte');
insert into login_comuna values	(12,'Antofagasta');
insert into login_comuna values	(13,'Mejillones');
insert into login_comuna values	(14,'Sierra Gorda');
insert into login_comuna values	(15,'Taltal');
insert into login_comuna values	(16,'Calama');
insert into login_comuna values	(17,'Ollague');
insert into login_comuna values	(18,'San Pedro de Atacama');
insert into login_comuna values	(19,'María Elena');
insert into login_comuna values	(20,'Tocopilla');
insert into login_comuna values	(21,'Chañaral');
insert into login_comuna values	(22,'Diego de Almagro');
insert into login_comuna values	(23,'Caldera');
insert into login_comuna values	(24,'Copiapó');
insert into login_comuna values	(25,'Tierra Amarilla');
insert into login_comuna values	(26,'Alto del Carmen');
insert into login_comuna values	(27,'Freirina');
insert into login_comuna values	(28,'Huasco');
insert into login_comuna values	(29,'Vallenar');
insert into login_comuna values	(30,'Canela');
insert into login_comuna values	(31,'Illapel');
insert into login_comuna values	(32,'Los Vilos');
insert into login_comuna values	(33,'Salamanca');
insert into login_comuna values	(34,'Andacollo');
insert into login_comuna values	(35,'Coquimbo');
insert into login_comuna values	(36,'La Higuera');
insert into login_comuna values	(37,'La Serena');
insert into login_comuna values	(38,'Paihuaco');
insert into login_comuna values	(39,'Vicuña');
insert into login_comuna values	(40,'Combarbalá');
insert into login_comuna values	(41,'Monte Patria');
insert into login_comuna values	(42,'Ovalle');
insert into login_comuna values	(43,'Punitaqui');
insert into login_comuna values	(44,'Río Hurtado');
insert into login_comuna values	(45,'Isla de Pascua');
insert into login_comuna values	(46,'Calle Larga');
insert into login_comuna values	(47,'Los Andes');
insert into login_comuna values	(48,'Rinconada');
insert into login_comuna values	(49,'San Esteban');
insert into login_comuna values	(50,'La Ligua');
insert into login_comuna values	(51,'Papudo');
insert into login_comuna values	(52,'Petorca');
insert into login_comuna values	(53,'Zapallar');
insert into login_comuna values	(54,'Hijuelas');
insert into login_comuna values	(55,'La Calera');
insert into login_comuna values	(56,'La Cruz');
insert into login_comuna values	(57,'Limache');
insert into login_comuna values	(58,'Nogales');
insert into login_comuna values	(59,'Olmué');
insert into login_comuna values	(60,'Quillota');
insert into login_comuna values	(61,'Algarrobo');
insert into login_comuna values	(62,'Cartagena');
insert into login_comuna values	(63,'El Quisco');
insert into login_comuna values	(64,'El Tabo');
insert into login_comuna values	(65,'San Antonio');
insert into login_comuna values	(66,'Santo Domingo');
insert into login_comuna values	(67,'Catemu');
insert into login_comuna values	(68,'Llaillay');
insert into login_comuna values	(69,'Panquehue');
insert into login_comuna values	(70,'Putaendo');
insert into login_comuna values	(71,'San Felipe');
insert into login_comuna values	(72,'Santa María');
insert into login_comuna values	(73,'Casablanca');
insert into login_comuna values	(74,'Concón');
insert into login_comuna values	(75,'Juan Fernández');
insert into login_comuna values	(76,'Puchuncaví');
insert into login_comuna values	(77,'Quilpué');
insert into login_comuna values	(78,'Quintero');
insert into login_comuna values	(79,'Valparaíso');
insert into login_comuna values	(80,'Villa Alemana');
insert into login_comuna values	(81,'Viña del Mar');
insert into login_comuna values	(82,'Colina');
insert into login_comuna values	(83,'Lampa');
insert into login_comuna values	(84,'Tiltil');
insert into login_comuna values	(85,'Pirque');
insert into login_comuna values	(86,'Puente Alto');
insert into login_comuna values	(87,'San José de Maipo');
insert into login_comuna values	(88,'Buin');
insert into login_comuna values	(89,'Calera de Tango');
insert into login_comuna values	(90,'Paine');
insert into login_comuna values	(91,'San Bernardo');
insert into login_comuna values	(92,'Alhué');
insert into login_comuna values	(93,'Curacaví');
insert into login_comuna values	(94,'María Pinto');
insert into login_comuna values	(95,'Melipilla');
insert into login_comuna values	(96,'San Pedro');
insert into login_comuna values	(97,'Cerrillos');
insert into login_comuna values	(98,'Cerro Navia');
insert into login_comuna values	(99,'Conchalí');
insert into login_comuna values	(100,'El Bosque');
insert into login_comuna values	(101,'Estación Central');
insert into login_comuna values	(102,'Huechuraba');
insert into login_comuna values	(103,'Independencia');
insert into login_comuna values	(104,'La Cisterna');
insert into login_comuna values	(105,'La Granja');
insert into login_comuna values	(106,'La Florida');
insert into login_comuna values	(107,'La Pintana');
insert into login_comuna values	(108,'La Reina');
insert into login_comuna values	(109,'Las Condes');
insert into login_comuna values	(110,'Lo Barnechea');
insert into login_comuna values	(111,'Lo Espejo');
insert into login_comuna values	(112,'Lo Prado');
insert into login_comuna values	(113,'Macul');
insert into login_comuna values	(114,'Maipú');
insert into login_comuna values	(115,'Ñuñoa');
insert into login_comuna values	(116,'Pedro Aguirre Cerda');
insert into login_comuna values	(117,'Peñalolén');
insert into login_comuna values	(118,'Providencia');
insert into login_comuna values	(119,'Pudahuel');
insert into login_comuna values	(120,'Quilicura');
insert into login_comuna values	(121,'Quinta Normal');
insert into login_comuna values	(122,'Recoleta');
insert into login_comuna values	(123,'Renca');
insert into login_comuna values	(124,'San Miguel');
insert into login_comuna values	(125,'San Joaquín');
insert into login_comuna values	(126,'San Ramón');
insert into login_comuna values	(127,'Santiago');
insert into login_comuna values	(128,'Vitacura');
insert into login_comuna values	(129,'El Monte');
insert into login_comuna values	(130,'Isla de Maipo');
insert into login_comuna values	(131,'Padre Hurtado');
insert into login_comuna values	(132,'Peñaflor');
insert into login_comuna values	(133,'Talagante');
insert into login_comuna values	(134,'Codegua');
insert into login_comuna values	(135,'Coínco');
insert into login_comuna values	(136,'Coltauco');
insert into login_comuna values	(137,'Doñihue');
insert into login_comuna values	(138,'Graneros');
insert into login_comuna values	(139,'Las Cabras');
insert into login_comuna values	(140,'Machalí');
insert into login_comuna values	(141,'Malloa');
insert into login_comuna values	(142,'Mostazal');
insert into login_comuna values	(143,'Olivar');
insert into login_comuna values	(144,'Peumo');
insert into login_comuna values	(145,'Pichidegua');
insert into login_comuna values	(146,'Quinta de Tilcoco');
insert into login_comuna values	(147,'Rancagua');
insert into login_comuna values	(148,'Rengo');
insert into login_comuna values	(149,'Requínoa');
insert into login_comuna values	(150,'San Vicente de Tagua Tagua');
insert into login_comuna values	(151,'La Estrella');
insert into login_comuna values	(152,'Litueche');
insert into login_comuna values	(153,'Marchihue');
insert into login_comuna values	(154,'Navidad');
insert into login_comuna values	(155,'Paredones');
insert into login_comuna values	(156,'Pichilemu');
insert into login_comuna values	(157,'Chépica');
insert into login_comuna values	(158,'Chimbarongo');
insert into login_comuna values	(159,'Lolol');
insert into login_comuna values	(160,'Nancagua');
insert into login_comuna values	(161,'Palmilla');
insert into login_comuna values	(162,'Peralillo');
insert into login_comuna values	(163,'Placilla');
insert into login_comuna values	(164,'Pumanque');
insert into login_comuna values	(165,'San Fernando');
insert into login_comuna values	(166,'Santa Cruz');
insert into login_comuna values	(167,'Cauquenes');
insert into login_comuna values	(168,'Chanco');
insert into login_comuna values	(169,'Pelluhue');
insert into login_comuna values	(170,'Curicó');
insert into login_comuna values	(171,'Hualañé');
insert into login_comuna values	(172,'Licantén');
insert into login_comuna values	(173,'Molina');
insert into login_comuna values	(174,'Rauco');
insert into login_comuna values	(175,'Romeral');
insert into login_comuna values	(176,'Sagrada Familia');
insert into login_comuna values	(177,'Teno');
insert into login_comuna values	(178,'Vichuquén');
insert into login_comuna values	(179,'Colbún');
insert into login_comuna values	(180,'Linares');
insert into login_comuna values	(181,'Longaví');
insert into login_comuna values	(182,'Parral');
insert into login_comuna values	(183,'Retiro');
insert into login_comuna values	(184,'San Javier');
insert into login_comuna values	(185,'Villa Alegre');
insert into login_comuna values	(186,'Yerbas Buenas');
insert into login_comuna values	(187,'Constitución');
insert into login_comuna values	(188,'Curepto');
insert into login_comuna values	(189,'Empedrado');
insert into login_comuna values	(190,'Maule');
insert into login_comuna values	(191,'Pelarco');
insert into login_comuna values	(192,'Pencahue');
insert into login_comuna values	(193,'Río Claro');
insert into login_comuna values	(194,'San Clemente');
insert into login_comuna values	(195,'San Rafael');
insert into login_comuna values	(196,'Talca');
insert into login_comuna values	(197,'Arauco');
insert into login_comuna values	(198,'Cañete');
insert into login_comuna values	(199,'Contulmo');
insert into login_comuna values	(200,'Curanilahue');
insert into login_comuna values	(201,'Lebu');
insert into login_comuna values	(202,'Los Álamos');
insert into login_comuna values	(203,'Tirúa');
insert into login_comuna values	(204,'Alto Biobío');
insert into login_comuna values	(205,'Antuco');
insert into login_comuna values	(206,'Cabrero');
insert into login_comuna values	(207,'Laja');
insert into login_comuna values	(208,'Los Ángeles');
insert into login_comuna values	(209,'Mulchén');
insert into login_comuna values	(210,'Nacimiento');
insert into login_comuna values	(211,'Negrete');
insert into login_comuna values	(212,'Quilaco');
insert into login_comuna values	(213,'Quilleco');
insert into login_comuna values	(214,'San Rosendo');
insert into login_comuna values	(215,'Santa Bárbara');
insert into login_comuna values	(216,'Tucapel');
insert into login_comuna values	(217,'Yumbel');
insert into login_comuna values	(218,'Chiguayante');
insert into login_comuna values	(219,'Concepción');
insert into login_comuna values	(220,'Coronel');
insert into login_comuna values	(221,'Florida');
insert into login_comuna values	(222,'Hualpén');
insert into login_comuna values	(223,'Hualqui');
insert into login_comuna values	(224,'Lota');
insert into login_comuna values	(225,'Penco');
insert into login_comuna values	(226,'San Pedro de La Paz');
insert into login_comuna values	(227,'Santa Juana');
insert into login_comuna values	(228,'Talcahuano');
insert into login_comuna values	(229,'Tomé');
insert into login_comuna values	(230,'Bulnes');
insert into login_comuna values	(231,'Chillán');
insert into login_comuna values	(232,'Chillán Viejo');
insert into login_comuna values	(233,'Cobquecura');
insert into login_comuna values	(234,'Coelemu');
insert into login_comuna values	(235,'Coihueco');
insert into login_comuna values	(236,'El Carmen');
insert into login_comuna values	(237,'Ninhue');
insert into login_comuna values	(238,'Ñiquen');
insert into login_comuna values	(239,'Pemuco');
insert into login_comuna values	(240,'Pinto');
insert into login_comuna values	(241,'Portezuelo');
insert into login_comuna values	(242,'Quillón');
insert into login_comuna values	(243,'Quirihue');
insert into login_comuna values	(244,'Ránquil');
insert into login_comuna values	(245,'San Carlos');
insert into login_comuna values	(246,'San Fabián');
insert into login_comuna values	(247,'San Ignacio');
insert into login_comuna values	(248,'San Nicolás');
insert into login_comuna values	(249,'Treguaco');
insert into login_comuna values	(250,'Yungay');
insert into login_comuna values	(251,'Carahue');
insert into login_comuna values	(252,'Cholchol');
insert into login_comuna values	(253,'Cunco');
insert into login_comuna values	(254,'Curarrehue');
insert into login_comuna values	(255,'Freire');
insert into login_comuna values	(256,'Galvarino');
insert into login_comuna values	(257,'Gorbea');
insert into login_comuna values	(258,'Lautaro');
insert into login_comuna values	(259,'Loncoche');
insert into login_comuna values	(260,'Melipeuco');
insert into login_comuna values	(261,'Nueva Imperial');
insert into login_comuna values	(262,'Padre Las Casas');
insert into login_comuna values	(263,'Perquenco');
insert into login_comuna values	(264,'Pitrufquén');
insert into login_comuna values	(265,'Pucón');
insert into login_comuna values	(266,'Saavedra');
insert into login_comuna values	(267,'Temuco');
insert into login_comuna values	(268,'Teodoro Schmidt');
insert into login_comuna values	(269,'Toltén');
insert into login_comuna values	(270,'Vilcún');
insert into login_comuna values	(271,'Villarrica');
insert into login_comuna values	(272,'Angol');
insert into login_comuna values	(273,'Collipulli');
insert into login_comuna values	(274,'Curacautín');
insert into login_comuna values	(275,'Ercilla');
insert into login_comuna values	(276,'Lonquimay');
insert into login_comuna values	(277,'Los Sauces');
insert into login_comuna values	(278,'Lumaco');
insert into login_comuna values	(279,'Purén');
insert into login_comuna values	(280,'Renaico');
insert into login_comuna values	(281,'Traiguén');
insert into login_comuna values	(282,'Victoria');
insert into login_comuna values	(283,'Corral');
insert into login_comuna values	(284,'Lanco');
insert into login_comuna values	(285,'Los Lagos');
insert into login_comuna values	(286,'Máfil');
insert into login_comuna values	(287,'Mariquina');
insert into login_comuna values	(288,'Paillaco');
insert into login_comuna values	(289,'Panguipulli');
insert into login_comuna values	(290,'Valdivia');
insert into login_comuna values	(291,'Futrono');
insert into login_comuna values	(292,'La Unión');
insert into login_comuna values	(293,'Lago Ranco');
insert into login_comuna values	(294,'Río Bueno');
insert into login_comuna values	(295,'Ancud');
insert into login_comuna values	(296,'Castro');
insert into login_comuna values	(297,'Chonchi');
insert into login_comuna values	(298,'Curaco de Vélez');
insert into login_comuna values	(299,'Dalcahue');
insert into login_comuna values	(300,'Puqueldón');
insert into login_comuna values	(301,'Queilén');
insert into login_comuna values	(302,'Quemchi');
insert into login_comuna values	(303,'Quellón');
insert into login_comuna values	(304,'Quinchao');
insert into login_comuna values	(305,'Calbuco');
insert into login_comuna values	(306,'Cochamó');
insert into login_comuna values	(307,'Fresia');
insert into login_comuna values	(308,'Frutillar');
insert into login_comuna values	(309,'Llanquihue');
insert into login_comuna values	(310,'Los Muermos');
insert into login_comuna values	(311,'Maullín');
insert into login_comuna values	(312,'Puerto Montt');
insert into login_comuna values	(313,'Puerto Varas');
insert into login_comuna values	(314,'Osorno');
insert into login_comuna values	(315,'Puerto Octay');
insert into login_comuna values	(316,'Purranque');
insert into login_comuna values	(317,'Puyehue');
insert into login_comuna values	(318,'Río Negro');
insert into login_comuna values	(319,'San Juan de la Costa');
insert into login_comuna values	(320,'San Pablo');
insert into login_comuna values	(321,'Chaitén');
insert into login_comuna values	(322,'Futaleufú');
insert into login_comuna values	(323,'Hualaihué');
insert into login_comuna values	(324,'Palena');
insert into login_comuna values	(325,'Aysén');
insert into login_comuna values	(326,'Cisnes');
insert into login_comuna values	(327,'Guaitecas');
insert into login_comuna values	(328,'Cochrane');
insert into login_comuna values	(329,'O''higgins');
insert into login_comuna values	(330,'Tortel');
insert into login_comuna values	(331,'Coyhaique');
insert into login_comuna values	(332,'Lago Verde');
insert into login_comuna values	(333,'Chile Chico');
insert into login_comuna values	(334,'Río Ibáñez');
insert into login_comuna values	(335,'Antártica');
insert into login_comuna values	(336,'Cabo de Hornos');
insert into login_comuna values	(337,'Laguna Blanca');
insert into login_comuna values	(338,'Punta Arenas');
insert into login_comuna values	(339,'Río Verde');
insert into login_comuna values	(340,'San Gregorio');
insert into login_comuna values	(341,'Porvenir');
insert into login_comuna values	(342,'Primavera');
insert into login_comuna values	(343,'Timaukel');
insert into login_comuna values	(344,'Natales');
insert into login_comuna values	(345,'Torres del Paine');
insert into login_comuna values	(346,'Cabildo');




drop table DJANGO_MIGRATIONS;
drop table DJANGO_CONTENT_TYPE;
drop table AUTH_PERMISSION;
drop table AUTH_GROUP;
drop table AUTH_GROUP_PERMISSIONS;
drop table AUTH_USER;
drop table AUTH_USER_GROUPS;
drop table AUTH_USER_USER_PERMISSIONS;
drop table DJANGO_ADMIN_LOG;
drop table MODULOLOGIN_REGION;
drop table DJANGO_SESSION;
