# Generated by Django 4.0.5 on 2022-07-09 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='apellido_materno')),
                ('rut', models.CharField(max_length=15, verbose_name='rut')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('comuna', models.CharField(max_length=50, verbose_name='comuna')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
